In [2]:
A = [1, 2; 3, 4; 5, 6]
B = [11, 12; 13, 14; 15, 16]
C = [1 1; 2 2]

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

C =

   1   1
   2   2



In [3]:
A * C

ans =

    5    5
   11   11
   17   17



In [5]:
A .* B  % Element wise multiply

ans =

   11   24
   39   56
   75   96



In [6]:
A .^ 2  % element wise square

ans =

    1    4
    9   16
   25   36



In [9]:
v = [1; 2; 3];
1 ./ v  % element wise reciprocal

ans =

   1.00000
   0.50000
   0.33333



In [13]:
log(v)
exp(v)
abs(v)
-v

ans =

   0.00000
   0.69315
   1.09861

ans =

    2.7183
    7.3891
   20.0855

ans =

   1
   2
   3

ans =

  -1
  -2
  -3



In [14]:
v + ones(length(v), 1)

ans =

   2
   3
   4



In [15]:
v + 1

ans =

   2
   3
   4



In [17]:
A'  % Transpose
(A')'

ans =

   1   3   5
   2   4   6

ans =

   1   2
   3   4
   5   6



In [25]:
a = [1 15 2 0.5]

a =

    1.00000   15.00000    2.00000    0.50000



In [27]:
val = max(a);
[val, ind] = max(a)

val =  15
ind =  2


In [29]:
a < 3  % elemnt wise comparison

ans =

  1  0  1  1



In [30]:
find(a < 3)  % Find actual elements

ans =

   1   3   4



In [31]:
A = magic(3)  % All rows, cols and diagonals sum to same thing

A =

   8   1   6
   3   5   7
   4   9   2



In [33]:
[r, c] = find(A >= 7)  % 1,1 - 3,2 - 2,3

r =

   1
   3
   2

c =

   1
   2
   3



In [37]:
sum(a)
prod(a)  % product
floor(a)
ceil(a)

ans =  18.500
ans =  15
ans =

    1   15    2    0

ans =

    1   15    2    1



In [39]:
max(rand(3), rand(3))  % elementwise max of two matrixes

ans =

   0.91619   0.48551   0.82153
   0.90384   0.89404   0.97255
   0.32906   0.83760   0.80657



In [44]:
A
max(A, [], 1)  % Column wise maximum
max(A, [], 2)  % Row wise maximum
max(max(A))  % all max

A =

   8   1   6
   3   5   7
   4   9   2

ans =

   8   9   7

ans =

   8
   7
   9

ans =  9


In [46]:
A = magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [47]:
sum(A, 1)  % all the same

ans =

   369   369   369   369   369   369   369   369   369



In [49]:
sum(A, 2)   % all the same

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [52]:
A .* eye(9)  % just diagonal elements

ans =

   47    0    0    0    0    0    0    0    0
    0   68    0    0    0    0    0    0    0
    0    0    8    0    0    0    0    0    0
    0    0    0   20    0    0    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0    0    0   62    0    0    0
    0    0    0    0    0    0   74    0    0
    0    0    0    0    0    0    0   14    0
    0    0    0    0    0    0    0    0   35



In [54]:
sum(sum(A .* eye(9)))  % sum all these numbers

ans =  369


In [59]:
flipud(eye(9))  % flip vertically

ans =

Permutation Matrix

   0   0   0   0   0   0   0   0   1
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   1   0   0   0   0   0   0   0   0



In [60]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [62]:
A_inv = pinv(A)  % inverse

A_inv =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778



In [64]:
A_inv * A  % essentially the identity matrix

ans =

   1.0000e+00   2.0817e-16  -3.1641e-15
  -6.1062e-15   1.0000e+00   6.2450e-15
   3.0531e-15   4.1633e-17   1.0000e+00

